spring:
#  datasource:
#    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
#    url: jdbc:cubrid:172.31.201.17:33000:sampledb:dba::?charSet=utf-8
#    username: dba

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: "jdbc:h2:mem:social_server;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa

  sql:
    init:
      platform: cubrid
      schema-locations: classpath:schema.sql
      data-locations: classpath:data-h2.sql
#
#mybatis:
#  mapper-locations: mapper/*.xml